language: node_js
node_js:
  - 4.2.0
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "X0Y8LvOkm6c/Eb/i2y863yuZVGJueWa/36j8bqzhIhx9cX7dCiC/27/gUF79STfA3oGYDIuY4s152vXpRO23xiaHlWy4MumihNmnwN2X0t7ieEFyyE1gXRjwWhGEDNJJ4zxOKu2yJk8D3ZNCLkGxPxAuQZaC2+TOAoiyxBI/+CMtck9M3AFoKiEPuGAbsLn0Be1/b7Vhv/4YlaKr/cZITqqlklc9LLiXrFGvCAGD10OC46NIkR3kV27sf4+scC+jY8u234YRq4aVS0FFVlkN6iQWzjx8cj1Q5PoAgdx5md8axg41LmQ/wYlsDZkSf8I0954NqtkTWLcCiclw0fDc4l+luV4B9U+vy72iE7qokgT9aXsQyOCwyQlPmcHB/KB6JGKvXqqz0C4qBPFzBahNfQRrFP1ITW4rPST76/1J2QUhy84K2tfPaSdjoi5wXdZ2OJBmdYJgz55D3CYH70p1tzZnxygjQNGRuQATaL3Hb5MNq+nKe/DUcWZ1ew0YX4oT8vrZckAyxjZ50Z8KaAzqh0XAWnAOk2S4YOTM2q38mEzkBg0qXojHy9+HUDZCQzq7SLb6eE5PSdjlABCmpM816tq8vD55dRNmmSKqfgZZUTDn7mxNOaePmNEoQyYcEGTgnirLGN9SnMIfg76RsoEW9w8NcXPJTg24GwYHtugfWHs="