language: node_js
node_js:
  - 0.12
  - 0.11
  - 0.10
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token: 8bcb1f339dda49b632673a2bb72f576054682fb9154f4b57841ad0ff22e96603